CREATE TABLE asset (
	asset_id INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT UNIQUE,
	asset_name TEXT NOT NULL UNIQUE,
    asset_value INTEGER NOT NULL UNIQUE,
    date_aquired DATETIME DEFAULT CURRENT_TIMESTAMP
);